networks:
  my-network:
    driver: bridge

services:
  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    command: sh -c "pnpm prisma migrate deploy --schema apps/reservations/prisma/schema.prisma && pnpm prisma generate --schema apps/reservations/prisma/schema.prisma && pnpm run start:dev reservations"
    env_file:
      - ./apps/reservations/.env
    ports:
      - "4001:4001"
    volumes:
      - .:/usr/src/app
    restart: always
    networks:
      - my-network
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: sh -c "pnpm prisma migrate deploy --schema apps/auth/prisma/schema.prisma && pnpm prisma generate --schema apps/auth/prisma/schema.prisma && pnpm run start:dev auth"
    env_file:
      - ./apps/auth/.env
    ports:
      - "4000:4000"
    volumes:
      - .:/usr/src/app
    restart: always
    networks:
      - my-network
#  twilio:
#    build:
#      context: .
#      dockerfile: ./apps/twilio/Dockerfile
#      target: development
#    command: sh -c "pnpm prisma migrate deploy --schema apps/twilio/prisma/schema.prisma && pnpm prisma generate --schema apps/twilio/prisma/schema.prisma && pnpm run start:dev twilio"
#    env_file:
#      - ./apps/twilio/.env
#    ports:
#      - "6007:6007"
#    volumes:
#      - .:/usr/src/app
#  payments:
#    build:
#      context: .
#      dockerfile: ./apps/payments/Dockerfile
#      target: development
#    command: sh -c "pnpm prisma migrate deploy --schema apps/payments/prisma/schema.prisma && pnpm prisma generate --schema apps/payments/prisma/schema.prisma && pnpm run start:dev payments"
#    env_file:
#      - ./apps/payments/.env
#    ports:
#      - "4003:4003"
#    volumes:
#      - .:/usr/src/app
#    restart: always
#    networks:
#      - my-network
  notifications:
    build:
      context: .
      dockerfile: ./apps/notifications/Dockerfile
      target: development
    command: pnpm run start:dev notifications
    env_file:
      - ./apps/notifications/.env
    ports:
      - "4002:4002"
    volumes:
      - .:/usr/src/app
    restart: always
    networks:
      - my-network
#  orders:
#    build:
#      context: .
#      dockerfile: ./apps/orders/Dockerfile
#      target: development
#    command: sh -c "pnpm prisma migrate deploy --schema apps/orders/prisma/schema.prisma && pnpm prisma generate --schema apps/orders/prisma/schema.prisma && pnpm run start:dev orders"
#    env_file:
#      - ./apps/orders/.env
#    ports:
#      - "6005:6005"
#    volumes:
#      - .:/usr/src/app
#  products:
#    build:
#      context: .
#      dockerfile: ./apps/products/Dockerfile
#      target: development
#    command: sh -c "pnpm prisma migrate deploy --schema apps/products/prisma/schema.prisma && pnpm prisma generate --schema apps/products/prisma/schema.prisma && pnpm run start:dev products"
#    env_file:
#      - ./apps/products/.env
#    ports:
#      - "6006:6006"
#    volumes:
#      - .:/usr/src/app
  gateway:
    build:
      context: .
      dockerfile: ./apps/gateway/Dockerfile
      target: development
    command: pnpm run start:dev gateway
    env_file:
      - ./apps/gateway/.env
    ports:
      - '4100:4100'
    volumes:
      - .:/usr/src/app
    restart: always
    networks:
      - my-network
